### ISSUE TITLE
Support responses other than application/json

### ISSUE THREAD

**Issue by BryceBarbara** [Eywek/oatyp#3]
I've encountered API endpoints that the endpoint responses are simply `text/plain` and it looks like there are a lot of hard-coded assumptions that the responses will be `application/json`. Is it possible to support string responses?

It looks like the main problem is the null exception on the following line: https://github.com/Eywek/oatyp/blob/main/src/api.ts#L136

**Comment by Eywek** [comment]
Fixed in https://github.com/Eywek/oatyp/pull/6
