### ISSUE TITLE
Ensure outDir exists before trying to write files

### ISSUE THREAD

**Issue by BryceBarbara** [Eywek/oatyp#4]
https://github.com/Eywek/oatyp/blob/main/src/index.ts#L106

Error Output:
```
Unable to generate: [Error: ENOENT: no such file or directory, open ...
```

To fix it, simply check to make sure the directory exists using `fileSystem` and create it if it's missing.

**Comment by Eywek** [comment]
Fixed in https://github.com/Eywek/oatyp/pull/6
