### ISSUE TITLE
Support endpoints with no response content

### ISSUE THREAD

**Issue by BryceBarbara** [Eywek/oatyp#5]
There are endpoints that don't return any content, for example, some `DELETE` requests return [HTTP 204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204).

There are few places I had to update to fix it locally, but the first error was triggered here:
https://github.com/Eywek/oatyp/blob/main/src/api.ts#L81

**Comment by Eywek** [comment]
Fixed in https://github.com/Eywek/oatyp/pull/6
